### ISSUE TITLE
Track Parcel Layer Clicks in Parcel Counter

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#199] opened 2019-05-30 15:06 UTC
### Subject of the issue
When a user clicks the parcel layer have it increment the Team parcel counter. Right now these clicks are not tracked.

**Comment by eanderson4** [comment] 2019-05-30 16:23
This is a duplicate of #156

**Closed by eanderson4** 2019-05-30 16:23 UTC
